In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [ ]:
df=pd.read_csv('../data/pakistan_data01.csv')
df

In [50]:
df.head()

,adm_lvl_1,adm_lvl_2,adm_lvl_3,adm_lvl_4,area_name,area_type,area_sq_km,total_pop,total_male,total_female,total_trans,sex_ratio,pop_density,pct_urban,avg_hh_size,total_pop_98,avg_annual_growth
0,BALOCHISTAN,NaN,NaN,NaN,BALOCHISTAN,TOTAL,347190.0,12335129.0,6483736.0,5850613.0,780.0,110.82,35.53,0.2762,6.87,6565885.0,0.0337
1,BALOCHISTAN,NaN,NaN,NaN,BALOCHISTAN,RURAL,NaN,8928428.0,4685756.0,4242183.0,489.0,110.46,NaN,NaN,6.80,4997105.0,0.0310
2,BALOCHISTAN,NaN,NaN,NaN,BALOCHISTAN,URBAN,NaN,3406701.0,1797980.0,1608430.0,291.0,111.78,NaN,NaN,7.06,1568780.0,0.0416
3,BALOCHISTAN,NaN,AWARAN,NaN,AWARAN DISTRICT,TOTAL,29510.0,121821.0,63063.0,58749.0,9.0,107.34,4.13,0.2810,6.61,118173.0,0.0016
4,BALOCHISTAN,NaN,AWARAN,NaN,AWARAN DISTRICT,RURAL,NaN,87584.0,45438.0,42138.0,8.0,107.83,NaN,NaN,6.25,118173.0,-0.0156

In [51]:
df.shape

(2073, 17)

In [52]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2073 entries, 0 to 2072
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   adm_lvl_1          2073 non-null   str
 1   adm_lvl_2          879 non-null    str
 2   adm_lvl_3          2007 non-null   str
 3   adm_lvl_4          1608 non-null   str
 4   area_name          2073 non-null   str
 5   area_type          2073 non-null   str
 6   area_sq_km         684 non-null    float64
 7   total_pop          1859 non-null   float64
 8   total_male         1859 non-null   float64
 9   total_female       1859 non-null   float64
 10  total_trans        1642 non-null   float64
 11  sex_ratio          1862 non-null   float64
 12  pop_density        682 non-null    float64
 13  pct_urban          518 non-null    float64
 14  avg_hh_size        1837 non-null   float64
 15  total_pop_98       1835 non-null   float64
 16  avg_annual_growth  1832 non-null   float64
dtypes: float64(11), str(6)
memory usage: 275.4 KB

In [ ]:
#checking duplicated values
df.duplicated().sum()

np.int64(0)

In [54]:
#cheking missing values
df.isnull().sum()

adm_lvl_1               0
adm_lvl_2            1194
adm_lvl_3              66
adm_lvl_4             465
area_name               0
area_type               0
area_sq_km           1389
total_pop             214
total_male            214
total_female          214
total_trans           431
sex_ratio             211
pop_density          1391
pct_urban            1555
avg_hh_size           236
total_pop_98          238
avg_annual_growth     241
dtype: int64

In [56]:
#checking the percentage of missing values
df.isnull().sum()/2073*100

adm_lvl_1             0.000000
adm_lvl_2            57.597685
adm_lvl_3             3.183792
adm_lvl_4            22.431259
area_name             0.000000
area_type             0.000000
area_sq_km           67.004342
total_pop            10.323203
total_male           10.323203
total_female         10.323203
total_trans          20.791124
sex_ratio            10.178485
pop_density          67.100820
pct_urban            75.012060
avg_hh_size          11.384467
total_pop_98         11.480945
avg_annual_growth    11.625663
dtype: float64

In [57]:
df.describe()

,area_sq_km,total_pop,total_male,total_female,total_trans,sex_ratio,pop_density,pct_urban,avg_hh_size,total_pop_98,avg_annual_growth
count,684.000000,1.859000e+03,1.859000e+03,1.859000e+03,1642.000000,1862.00000,682.000000,518.000000,1837.000000,1.835000e+03,1832.000000
mean,3892.381579,8.171552e+05,4.176485e+05,3.994215e+05,96.462850,106.02753,2019.055944,0.408385,6.579777,5.303512e+05,0.029659
std,17126.528751,3.788923e+06,1.931531e+06,1.857251e+06,455.241897,10.27526,8658.409604,2.214225,1.214435,2.527317e+06,0.222095
min,4.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.00000,1.380000,0.000000,0.000000,0.000000e+00,-1.000000
25%,530.500000,7.375800e+04,3.756450e+04,3.545900e+04,7.000000,102.54250,87.525000,0.149100,5.800000,4.712200e+04,0.016900
50%,1212.000000,2.314590e+05,1.189160e+05,1.139360e+05,23.000000,105.70000,340.455000,0.229500,6.310000,1.496150e+05,0.023200
75%,2782.500000,5.646050e+05,2.876630e+05,2.751375e+05,61.000000,108.64750,657.755000,0.362100,7.170000,3.692155e+05,0.030600
max,347190.000000,1.099897e+08,5.590977e+07,5.406745e+07,12435.000000,297.81000,110321.000000,50.370000,12.430000,7.362129e+07,6.960000

In [58]:
#to check the datatypes
df.dtypes

adm_lvl_1                str
adm_lvl_2                str
adm_lvl_3                str
adm_lvl_4                str
area_name                str
area_type                str
area_sq_km           float64
total_pop            float64
total_male           float64
total_female         float64
total_trans          float64
sex_ratio            float64
pop_density          float64
pct_urban            float64
avg_hh_size          float64
total_pop_98         float64
avg_annual_growth    float64
dtype: object

In [59]:
df.columns

Index(['adm_lvl_1', 'adm_lvl_2', 'adm_lvl_3', 'adm_lvl_4', 'area_name',
       'area_type', 'area_sq_km', 'total_pop', 'total_male', 'total_female',
       'total_trans', 'sex_ratio', 'pop_density', 'pct_urban', 'avg_hh_size',
       'total_pop_98', 'avg_annual_growth'],
      dtype='str')

In [63]:
#Ye sirf un numerical columns ki missing values dikhayega jahan missingness around 10–21% hai.
df[[  'area_sq_km','total_pop', 'total_male', 'total_female',
       'total_trans', 'sex_ratio', 'pop_density', 'pct_urban', 'avg_hh_size',
       'total_pop_98', 'avg_annual_growth']].isnull().sum()

area_sq_km           1389
total_pop             214
total_male            214
total_female          214
total_trans           431
sex_ratio             211
pop_density          1391
pct_urban            1555
avg_hh_size           236
total_pop_98          238
avg_annual_growth     241
dtype: int64

In [64]:
cols = ['total_pop', 'total_male', 'total_female',
        'total_trans', 'sex_ratio', 'avg_hh_size',
        'total_pop_98', 'avg_annual_growth']

df[cols] = df[cols].fillna(df[cols].median())

In [65]:
df[cols].isnull().sum()

total_pop            0
total_male           0
total_female         0
total_trans          0
sex_ratio            0
avg_hh_size          0
total_pop_98         0
avg_annual_growth    0
dtype: int64

In [66]:
df.isnull().sum()

adm_lvl_1               0
adm_lvl_2            1194
adm_lvl_3              66
adm_lvl_4             465
area_name               0
area_type               0
area_sq_km           1389
total_pop               0
total_male              0
total_female            0
total_trans             0
sex_ratio               0
pop_density          1391
pct_urban            1555
avg_hh_size             0
total_pop_98            0
avg_annual_growth       0
dtype: int64

In [67]:
df[['adm_lvl_2','adm_lvl_3','adm_lvl_4']].isnull().sum()

adm_lvl_2    1194
adm_lvl_3      66
adm_lvl_4     465
dtype: int64

In [73]:
type(df)

list

In [ ]:
df=pd.read_csv('../data/pakistan_data01.csv')
df

In [76]:
type(df)

pandas.DataFrame

In [77]:
cols = ['adm_lvl_2', 'adm_lvl_3', 'adm_lvl_4']

df[cols] = df[cols].fillna('unknown')

In [78]:
df[cols].isnull().sum()

adm_lvl_2    0
adm_lvl_3    0
adm_lvl_4    0
dtype: int64

In [79]:
df.isnull().sum()

adm_lvl_1               0
adm_lvl_2               0
adm_lvl_3               0
adm_lvl_4               0
area_name               0
area_type               0
area_sq_km           1389
total_pop             214
total_male            214
total_female          214
total_trans           431
sex_ratio             211
pop_density          1391
pct_urban            1555
avg_hh_size           236
total_pop_98          238
avg_annual_growth     241
dtype: int64

In [80]:
cols = ['total_pop', 'total_male', 'total_female',
        'total_trans', 'sex_ratio', 'avg_hh_size',
        'total_pop_98', 'avg_annual_growth']

df[cols] = df[cols].fillna(df[cols].median())

In [81]:
df.isnull().sum()

adm_lvl_1               0
adm_lvl_2               0
adm_lvl_3               0
adm_lvl_4               0
area_name               0
area_type               0
area_sq_km           1389
total_pop               0
total_male              0
total_female            0
total_trans             0
sex_ratio               0
pop_density          1391
pct_urban            1555
avg_hh_size             0
total_pop_98            0
avg_annual_growth       0
dtype: int64

In [ ]:
df[['area_sq_km', 'area_type', 'area_sq_km',]].isna().sum()

area_sq_km    1389
area_type        0
pct_urban     1555
dtype: int64

In [86]:
df[['area_sq_km', 'pct_urban']].isna().sum()

area_sq_km    1389
pct_urban     1555
dtype: int64

In [87]:
df.isnull().sum()

adm_lvl_1               0
adm_lvl_2               0
adm_lvl_3               0
adm_lvl_4               0
area_name               0
area_type               0
area_sq_km           1389
total_pop               0
total_male              0
total_female            0
total_trans             0
sex_ratio               0
pop_density          1391
pct_urban            1555
avg_hh_size             0
total_pop_98            0
avg_annual_growth       0
dtype: int64

In [92]:
cols = ['area_sq_km','pop_density','pct_urban']
df[cols]=df[cols].fillna(df[cols].median())

In [93]:
df.isnull().sum()

adm_lvl_1            0
adm_lvl_2            0
adm_lvl_3            0
adm_lvl_4            0
area_name            0
area_type            0
area_sq_km           0
total_pop            0
total_male           0
total_female         0
total_trans          0
sex_ratio            0
pop_density          0
pct_urban            0
avg_hh_size          0
total_pop_98         0
avg_annual_growth    0
dtype: int64

In [96]:
df.duplicated().sum()

np.int64(0)

In [97]:
df.dtypes

adm_lvl_1                str
adm_lvl_2                str
adm_lvl_3                str
adm_lvl_4                str
area_name                str
area_type                str
area_sq_km           float64
total_pop            float64
total_male           float64
total_female         float64
total_trans          float64
sex_ratio            float64
pop_density          float64
pct_urban            float64
avg_hh_size          float64
total_pop_98         float64
avg_annual_growth    float64
dtype: object